In [1]:
import bnpy
import numpy as np
import os

import matplotlib
from matplotlib import pylab
import seaborn as sns
%matplotlib inline

np.set_printoptions(suppress=1, precision=3)

FIG_SIZE = (10, 5)
pylab.rcParams['figure.figsize'] = FIG_SIZE

In [2]:
X = np.array([[0, 0, 1],
              [0, 1, 0],
              [0, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 0, 0]])

X = np.random.random((6, 3))

In [3]:
doc_range = np.array([0, 3, 6])

In [4]:
dataset = bnpy.data.GroupXData(X, doc_range)

In [5]:
K = 3
bnpy.run(dataset,
         'FiniteHMM', 'Gauss', 'VB',
         K=K, output_path='/tmp/my_dataset/results/',
         nnzPerRowLP=2)

Dataset Summary:
GroupXData
  size: 2 units (documents)
  dimension: 3
Allocation Model:  None
Obs. Data  Model:  Gaussian with full covariance.
Obs. Data  Prior:  Gauss-Wishart on mean and covar of each cluster
  E[  mean[k] ] = 
   [ 0.  0.]  ...
  E[ covar[k] ] = 
  [[ 1.  0.]
   [ 0.  1.]] ...
Initialization:
  initname = randexamples
  K = 3 (number of clusters)
  seed = 1607680
  elapsed_time: 0.1 sec
Learn Alg: VB | task  1/1 | alg. seed: 1607680 | data order seed: 8541952
task_output_path: /tmp/my_dataset/results/1
1
1.11022302463e-16
0
5.55111512313e-17
        1/10 after      0 sec. |    118.4 MiB | K    3 | loss  3.350998942e+00 |  
0
0.0255456657494


AssertionError: 

In [6]:
np.load('before_respPair.npy')

array([[[ 0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ]],

       [[ 0.03 ,  0.011,  0.   ],
        [ 0.318,  0.634,  0.004],
        [ 0.001,  0.001,  0.   ]],

       [[ 0.307,  0.01 ,  0.032],
        [ 0.488,  0.084,  0.075],
        [ 0.004,  0.   ,  0.   ]]])

In [7]:
np.load('before_resp.npy')

array([[ 0.042,  0.957,  0.002],
       [ 0.349,  0.647,  0.004],
       [ 0.799,  0.095,  0.106]])

In [14]:
resp = np.load('after_resp.npy')

In [12]:
respPair = np.load('after_norm_respPair.npy')

In [10]:
np.load('before_norm_respPair.npy')

array([[[ 0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ]],

       [[ 0.03 ,  0.011,  0.   ],
        [ 0.318,  0.634,  0.   ],
        [ 0.   ,  0.   ,  0.   ]],

       [[ 0.307,  0.   ,  0.032],
        [ 0.488,  0.   ,  0.075],
        [ 0.   ,  0.   ,  0.   ]]])

In [13]:
respPair[1:].sum(axis=1)

array([[ 0.35 ,  0.65 ,  0.   ],
       [ 0.882,  0.   ,  0.118]])

In [15]:
resp

array([[ 0.042,  0.958,  0.   ],
       [ 0.351,  0.649,  0.   ],
       [ 0.882,  0.   ,  0.118]])

In [17]:
respPair[1:].sum(axis=2)

array([[ 0.042,  0.958,  0.   ],
       [ 0.376,  0.624,  0.   ]])